create table family
(
    id      INT NOT NULL generated BY DEFAULT AS IDENTITY,
    name    VARCHAR(100),
    address VARCHAR(255),
    PRIMARY KEY (id)

);

create table person
(
    id        INT NOT NULL generated BY DEFAULT AS IDENTITY,
    firstname VARCHAR(50),
    lastname  VARCHAR(50),
    family_id INT,
    PRIMARY KEY (id),
    FOREIGN KEY (family_id) REFERENCES family (id)
);
